### ISSUE TITLE
Unable to build client, I guess the reason is futures crate versioning has changed

### ISSUE THREAD

**Issue by godadada** [pandaman64/satysfi-playground#1]
Could you look into the following build errors?

./build.sh
error:     Updating crates.io index
    Updating git repository `https://github.com/pandaman64/ot.git`
    Updating git repository `https://github.com/koute/stdweb.git`
error: failed to select a version for the requirement `futures = "^0.2"`
  candidate versions found which didn't match: 0.1.25, 0.1.24, 0.1.23, ...
  location searched: crates.io index
required by package `client v0.1.0 (/home/dude/test/bk/futures/satysfi-playground/client)

**Comment by pandaman64** [comment]
Thank you for your attention!
I'm sorry that the experimental real-time editor client is abandoned and it's not used in the playground (but not removed from the repo).
If you're interested in testing the server, please try the following:

```
[/path/to/satysfi-playground]$ docker build -t pandaman64/satysfi-playground docker # build the compiler
[/path/to/satysfi-playground]$ cd server
[/path/to/satysfi-playground/server]$ cargo run
```

Then navigate to `localhost:8000`.

If a `futures-preview` related crate doesn't compile, try `cargo update` and the latest nightly.
You may find `RUST_LOG=actix_web=info` helpful for logging.
